      pipeline {
        agent any
        environment {
            REPORT_DIR = 'target/extent-reports'
            SCREENSHOT_DIR = 'target/screenshots'
        }

        stages {
           stage('Setup') {
              steps{
                script {
                echo "Creating directories for reports and screenshots..."
                sh "mkdir -p ${REPORT_DIR}"
                sh "mkdir -p ${SCREENSHOT_DIR}"
                }
              }
            }
           stage('Checkout') {
                steps {
                      git 'https://github.com/rshah160487/rshah-selenium-testng.git'
                      }
            }

           stage('Build') {
                steps {
                    echo 'Running build step...'
                    sh 'mvn clean compile'
                }
            }

           stage('Test') {
                steps {
                    echo 'Running tests...'
                    sh 'mvn test'
                }
            }

           stage('Generate Reports') {
                steps {
                    echo 'Generating reports...'
                    sh 'mvn site'
                }
            }

           stage('Archive Artifacts') {
                steps {
                    echo 'Archiving reports and screenshots...'
                    archiveArtifacts artifacts: "${REPORT_DIR}/**", fingerprint: true
                    publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true, reportDir: "${REPORT_DIR}", reportFiles: 'ExtentReport.html', reportName: 'Extent Report'])
                }
            }
        }

        post {
            always {
                echo 'Cleaning up workspace...'
                cleanWs()
            }
            success {
                echo 'Build succeeded!'
            }
            failure {
                echo 'Build failed!'
            }
        }
    }